# Generated by Django 5.0 on 2023-12-07 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_info_user_despesa_valor_despesa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='tipo_saldo',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='tipo_saldo',
        ),
        migrations.RenameField(
            model_name='meta',
            old_name='valor_meta',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='tipometa',
            old_name='tipo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='valor_despesa',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='id',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='valor_receita',
        ),
        migrations.AddField(
            model_name='despesa',
            name='local',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='metodo_pagamento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='descricao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='fonte',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='metodo_recebimento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dica',
            name='texto',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='meta',
            name='tipo_meta',
        ),
        migrations.AlterField(
            model_name='tipometa',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipodespesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo_receita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tiporeceita'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='transacao_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.transacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='transacao_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.transacao'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
        migrations.DeleteModel(
            name='TipoSaldo',
        ),
        migrations.AddField(
            model_name='meta',
            name='tipo_meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipometa'),
            preserve_default=False,
        ),
    ]
