-- Criar uma Database (Banco de Dados)
CREATE DATABASE AULABDI;

-- Faz uso desta Database
USE AULABDI;

-- Comando CREATE TABLE para CRIAR a TABELA FUNCIONARIOS
CREATE TABLE FUNCIONARIOS (
CODFUN INTEGER NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
DEPTO CHAR(2),
FUNCAO VARCHAR(20),
SALARIO DECIMAL(10,2)
);

-- Comando INSERT para inserir REGISTROS na TABELA
INSERT INTO FUNCIONARIOS (CODFUN,NOME,DEPTO,FUNCAO,SALARIO )
VALUES (12,'CARLOS ALBERTO','03','VENDEDOR',1530.00);

-- Comando SELECT - Visualiza APENAS o campo/atributo NOME da tabela FUNCIONARIOS
SELECT NOME FROM FUNCIONARIOS;

-- Comando SELECT - Visualiza TODOS os campos/atributos da tabela FUNCIONARIOS
SELECT * FROM FUNCIONARIOS ;

-- Comando INSERT 
INSERT INTO FUNCIONARIOS (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES (15,'MARCOS HENRIQUE','02','GERENTE',1985.75);

INSERT INTO FUNCIONARIOS (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES (7,'APARECIDA SILVA','03','SECRETARIA',1200.50);

INSERT INTO FUNCIONARIOS (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES (9,'SOLANGE PACHECO','05','SUPERVISORA',1599.51);

INSERT INTO FUNCIONARIOS (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES (6,'MARCELO SOUZA','03','ANALISTA',2250.11);

INSERT INTO FUNCIONARIOS (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES (1,'CELIA NASCIMENTO','02','SECRETARIA',1200.50);

-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;


-- Comando INSERT SIMPLIFICADO - Insere um REGISTRO na TABELA FUNCIONARIOS
INSERT INTO FUNCIONARIOS VALUES (2,'WILSON DE MACEDO','03','PROGRAMADOR',1050.00);

INSERT INTO FUNCIONARIOS VALUES (5,'AUGUSTO SOUZA','03','PROGRAMADOR',1050.00);
INSERT INTO FUNCIONARIOS VALUES (4,'CARLOS BASTOS','05','VENDEDOR',1530.00);
INSERT INTO FUNCIONARIOS VALUES (25,'PEDRO SILVA','03','SUPERVISOR',1599.51);
INSERT INTO FUNCIONARIOS VALUES (3,'ANA BASTOS','05','VENDEDORA',1530.00);
INSERT INTO FUNCIONARIOS VALUES (10,'PAULO DA SILVA','02','VENDEDOR',1530.00);

-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;

-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
-- ONDE o campo CODFUN (deste registro) for igual a 4...
SELECT * FROM FUNCIONARIOS WHERE CODFUN = 4; 

-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
-- ORDENADO pelo campo/atributo NOME de forma ASCENDENTE
SELECT * FROM FUNCIONARIOS ORDER BY NOME ASC;

-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
-- ORDENADO pelo campo/atributo DEPTO de forma DESCENDENTE
SELECT * FROM FUNCIONARIOS ORDER BY DEPTO DESC;



-- EXERCICIOS... --------------------------------------------------------

-- Comando SELECT - Visualiza os campos/atributos NOME e FUNCAO da TABELA FUNCIONARIOS
SELECT NOME, FUNCAO FROM FUNCIONARIOS;

-- Comando SELECT - Visualiza o campo/atributo da TABELA FUNCIONARIOS
-- ONDE o campo DEPTO (deste registro) for igual a 03...
SELECT NOME FROM FUNCIONARIOS WHERE DEPTO = '03';

-- Comando SELECT - Visualiza os campos/atributos NOME e SALARIO da TABELA FUNCIONARIOS
-- ORDENADO pelo campo/atributo NOME (de forma ASCENDENTE)
SELECT NOME,SALARIO FROM FUNCIONARIOS ORDER BY NOME;

-- Comando SELECT - Visualiza os campos/atributos NOME e SALARIO da TABELA FUNCIONARIOS
-- ORDENADO pelo campo/atributo NOME (de forma DESCENDENTE)
SELECT NOME,SALARIO FROM FUNCIONARIOS ORDER BY NOME DESC;

-- Comando SELECT - Visualiza os campos/atributos DEPTO e NOME da TABELA FUNCIONARIOS
-- ORDENADO, respectivamente, pelos campos/atributos DEPTO (ASCENDENTE) e NOME (DESCENDENTE)
SELECT DEPTO, NOME FROM FUNCIONARIOS ORDER BY DEPTO, NOME DESC ;

-- Comando SELECT - Visualiza o campo/atributo NOME da TABELA FUNCIONARIOS
-- ONDE o campo DEPTO (deste registro) for igual a 03...
-- ORDENADO pelo campo/atributo NOME (ASCENDENTE)
SELECT NOME FROM FUNCIONARIOS WHERE DEPTO = '03' ORDER BY NOME;

-- FIM EXERCICIOS... --------------------------------------------------------



-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
-- ONDE o campo CODFUN (deste registro) for igual a 7...
SELECT * FROM FUNCIONARIOS WHERE CODFUN = 7;
-- Comando UPDATE - Altera, na TABELA FUNCIONARIOS, o campo SALARIO para 2300.56 do registro
-- ONDE o campo CODFUN (deste registro) for igual a 7...
UPDATE FUNCIONARIOS SET SALARIO = 2300.56 WHERE CODFUN = 7;
-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
-- ONDE o campo CODFUN (deste registro) for igual a 7...
SELECT * FROM FUNCIONARIOS WHERE CODFUN = 7;

-- Comandos SELECT para Visualizar um DETERMINADO REGISTRO
-- Comandos UPDATE para Alterar este DETERMINADO REGISTRO
-- Comandos SELECT para Visualizar este REGISTRO Alterado
SELECT * FROM FUNCIONARIOS WHERE NOME='ANA BASTOS';
UPDATE FUNCIONARIOS SET DEPTO = '03' WHERE NOME ='ANA BASTOS';
SELECT * FROM FUNCIONARIOS WHERE NOME='ANA BASTOS';

SELECT * FROM FUNCIONARIOS;
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.10;
SELECT * FROM FUNCIONARIOS;



-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;
-- Comando DELETE - Exclui o REGISTRO da TABELA FUNCIONARIOS 
-- ONDE o campo DEPTO (deste registro) for igual a 02...
DELETE FROM FUNCIONARIOS WHERE DEPTO = '02';
-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;

-- Comandos SELECT para Visualizar um DETERMINADO REGISTRO
-- Comandos DELETE para Excluir este DETERMINADO REGISTRO
-- Comandos SELECT para Visualizar este REGISTRO Alterado
SELECT * FROM FUNCIONARIOS;
DELETE FROM FUNCIONARIOS WHERE NOME = 'MARCELO SOUZA';
SELECT * FROM FUNCIONARIOS;



-- Comando ALTER TABLE - Altera a estrutura da tabela FUNCIONARIOS 
-- ADICIONANDO o campo/atributo ADMISSAO do tipo DATE
ALTER TABLE FUNCIONARIOS ADD ADMISSAO DATE;
-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;



-- Comando UPDATE - Altera, na TABELA FUNCIONARIOS, o campo ADMISSAO 
-- atribuíndo-lhe um determinado valor PARA CADA Registro específico...
UPDATE FUNCIONARIOS SET ADMISSAO = '20060115' WHERE CODFUN = 2;
UPDATE FUNCIONARIOS SET ADMISSAO = '19990121' WHERE CODFUN = 3;
UPDATE FUNCIONARIOS SET ADMISSAO = '20041021' WHERE CODFUN = 4;
UPDATE FUNCIONARIOS SET ADMISSAO = '20060426' WHERE CODFUN = 5;
UPDATE FUNCIONARIOS SET ADMISSAO = '19800510' WHERE CODFUN = 7;
UPDATE FUNCIONARIOS SET ADMISSAO = '19991215' WHERE CODFUN = 9; 
UPDATE FUNCIONARIOS SET ADMISSAO = '20001221' WHERE CODFUN = 12;
UPDATE FUNCIONARIOS SET ADMISSAO = '20001221' WHERE CODFUN = 25;
-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;



-- Comando SELECT - Visualiza os campos/atributos NOME e ADMISSAO da TABELA FUNCIONARIOS
-- ONDE o campo ADMISSAO (deste registro) tiver o MES igual a 12...
SELECT NOME, ADMISSAO FROM FUNCIONARIOS WHERE MONTH(ADMISSAO) = 12;

-- Comando SELECT - Visualiza os campos/atributos NOME e ADMISSAO da TABELA FUNCIONARIOS
-- ONDE o campo ADMISSAO (deste registro) for MAIOR OU IGUAL a '20000101'...
SELECT NOME, ADMISSAO FROM FUNCIONARIOS WHERE ADMISSAO >= '20000101';



-- Comando INSERT - Insere os registros abaixo na tabela FUNCIONARIOS
INSERT INTO FUNCIONARIOS VALUES (15,'MARCOS HENRIQUE','02','GERENTE',2184.33,'20060525');
INSERT INTO FUNCIONARIOS VALUES (20,'AUDREY TOLEDO','02','SUPERVISORA',1700.00,'20060705');
INSERT INTO FUNCIONARIOS VALUES (22,'SANDRA MANZANO','02','ANALISTA',2000.00,'20060701');
INSERT INTO FUNCIONARIOS VALUES (24,'MARCIO CANUTO','02','PROGRAMADOR',1200.00,'20060710');

-- Comando SELECT - Visualiza todos os campos/atributos da TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;



-- querys
select * from funcionarios;

/* 18 */ select nome, salario, (salario * 1.2) from funcionarios;
/* 17 */ select nome from funcionarios where (admissao <= '2010-12-31') and funcao in ('PROGRAMADOR','supervisor')  ;
/* 16 */ select nome from funcionarios where (admissao >= '2000-01-01');
/* 15 */ select nome from funcionarios where funcao in ('supervisor','supervisora') and salario <= 2100;
/* 14 */ select nome from funcionarios where funcao in ('vendedor','vendedora');





