-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 19:51:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ForcaVendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ForcaVendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ForcaVendas` DEFAULT CHARACTER SET utf8 ;
USE `ForcaVendas` ;

-- -----------------------------------------------------
-- Table `ForcaVendas`.`comission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`comission` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`comission` (
  `idcomission` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL NULL,
  `triger` DECIMAL NULL,
  `reduction` DECIMAL NULL,
  PRIMARY KEY (`idcomission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`products` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`products` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(45) NULL,
  `price` DECIMAL NULL,
  `cust` DECIMAL NULL,
  `weight_gross` DECIMAL NULL,
  `default_discount` DECIMAL NULL,
  `max_discount` DECIMAL NULL,
  `limit_discount` DECIMAL NULL,
  `NCM` INT NULL,
  `ipi_value` DECIMAL NULL,
  `active` INT NULL,
  `comission_idcomission` INT NOT NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `fk_product_comission1_idx` (`comission_idcomission` ASC) VISIBLE,
  CONSTRAINT `fk_product_comission1`
    FOREIGN KEY (`comission_idcomission`)
    REFERENCES `ForcaVendas`.`comission` (`idcomission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`categories` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`categories` (
  `idcategories` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  `default_discount` DECIMAL(10,2) NULL,
  `max_discount` DECIMAL(10,2) NULL,
  `limit_discount` DECIMAL(10,2) NULL,
  `product_idproduct` INT NOT NULL,
  PRIMARY KEY (`idcategories`),
  INDEX `fk_categories_product1_idx` (`product_idproduct` ASC) VISIBLE,
  CONSTRAINT `fk_categories_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `ForcaVendas`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`store_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`store_region` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`store_region` (
  `idstore_region` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`idstore_region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`adress` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`adress` (
  `idadress` INT NOT NULL AUTO_INCREMENT,
  `road` VARCHAR(45) NULL,
  `number` VARCHAR(10) NULL,
  `neighborhood` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `store_region_idstore_region` INT NOT NULL,
  PRIMARY KEY (`idadress`),
  INDEX `fk_adress_store_region1_idx` (`store_region_idstore_region` ASC) VISIBLE,
  CONSTRAINT `fk_adress_store_region1`
    FOREIGN KEY (`store_region_idstore_region`)
    REFERENCES `ForcaVendas`.`store_region` (`idstore_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`segments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`segments` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`segments` (
  `idsegment` INT NOT NULL AUTO_INCREMENT,
  `segment_name` VARCHAR(45) NULL,
  `max_discount` DECIMAL NULL,
  `limit_discount` DECIMAL NULL,
  `default_discount` DECIMAL NULL,
  PRIMARY KEY (`idsegment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`stores` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`stores` (
  `idstore` INT NOT NULL AUTO_INCREMENT,
  `client_legal_name` VARCHAR(45) NULL,
  `client_name` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `IE` INT NULL,
  `type` VARCHAR(20) NULL,
  `client_since` DATETIME NULL,
  `default_discount` DECIMAL NULL,
  `is_active` INT NULL,
  `segment_idsegment` INT NOT NULL,
  `adress_idadress` INT NOT NULL,
  PRIMARY KEY (`idstore`),
  INDEX `fk_store_adress1_idx` (`adress_idadress` ASC) VISIBLE,
  INDEX `fk_store_segment1_idx` (`segment_idsegment` ASC) VISIBLE,
  CONSTRAINT `fk_store_adress1`
    FOREIGN KEY (`adress_idadress`)
    REFERENCES `ForcaVendas`.`adress` (`idadress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_segment1`
    FOREIGN KEY (`segment_idsegment`)
    REFERENCES `ForcaVendas`.`segments` (`idsegment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`orders` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`orders` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `dta_emission` DATETIME NULL,
  PRIMARY KEY (`idorder`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`invoice` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`invoice` (
  `idinvoice` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `date` DATETIME NULL,
  `number` INT NULL,
  `cfop` INT NULL,
  `operation` VARCHAR(45) NULL,
  `status` INT NULL,
  `order_idorder` INT NOT NULL,
  PRIMARY KEY (`idinvoice`),
  INDEX `fk_invoice_order1_idx` (`order_idorder` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `ForcaVendas`.`orders` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`order_itens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`order_itens` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`order_itens` (
  `order_idorder` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  `qty` DECIMAL NULL,
  PRIMARY KEY (`order_idorder`, `product_idproduct`),
  INDEX `fk_order_has_product_product1_idx` (`product_idproduct` ASC) VISIBLE,
  INDEX `fk_order_has_product_order1_idx` (`order_idorder` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `ForcaVendas`.`orders` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `ForcaVendas`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForcaVendas`.`salesman`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ForcaVendas`.`salesman` ;

CREATE TABLE IF NOT EXISTS `ForcaVendas`.`salesman` (
  `store_idstore` INT NOT NULL,
  `order_idorder` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` INT NULL,
  `active` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`store_idstore`, `order_idorder`),
  INDEX `fk_store_has_order_order1_idx` (`order_idorder` ASC) VISIBLE,
  INDEX `fk_store_has_order_store1_idx` (`store_idstore` ASC) VISIBLE,
  CONSTRAINT `fk_store_has_order_store1`
    FOREIGN KEY (`store_idstore`)
    REFERENCES `ForcaVendas`.`stores` (`idstore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_has_order_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `ForcaVendas`.`orders` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#============================================================================================================================================

INSERT INTO `ForcaVendas`.`products` (
  `name_product`,
  `price`,
  `cust`,
  `weight_gross`,
  `default_discount`,
  `max_discount`,
  `limit_discount`,
  `NCM`,
  `ipi_value`,
  `active`,
  `comission_idcomission`
) VALUES 
  ('Maça', 1.99, 1.00, 150.0, 0.02, 0.15, 0.10, 12345678, 0.50, 1, 1),
  ('Pão', 2.49, 1.50, 400.0, 0.03, 0.20, 0.15, 87654321, 0.30, 1, 1),
  ('Queijo', 5.99, 4.00, 250.0, 0.05, 0.25, 0.20, 56781234, 1.00, 1, 1),
  ('Chocolate', 3.50, 2.50, 100.0, 0.04, 0.18, 0.12, 34567812, 0.75, 1, 1),
  ('Pasta de amendoim', 2.99, 1.80, 300.0, 0.03, 0.15, 0.10, 23456781, 0.40, 1, 1),
  ('Frango', 8.99, 6.50, 800.0, 0.08, 0.30, 0.25, 78901234, 1.50, 1, 1),
  ('Tomate', 1.25, 0.80, 200.0, 0.02, 0.12, 0.08, 89012345, 0.25, 1, 1),
  ('Leite', 2.29, 1.80, 1000.0, 0.05, 0.25, 0.20, 45678901, 0.50, 1, 1),
  ('Cereal', 4.99, 3.50, 400.0, 0.04, 0.20, 0.15, 67890123, 0.80, 1, 1),
  ('Salmão', 12.99, 10.00, 600.0, 0.10, 0.35, 0.30, 90123456, 2.00, 1, 1);


INSERT INTO `ForcaVendas`.`comission` (
`value`, 
`triger`, 
`reduction`
) VALUES
  (0.05, 5000, 0.02),
  (0.08, 8000, 0.03),
  (0.10, 10000, 0.05);


INSERT INTO `ForcaVendas`.`categories` (
  `category_name`,
  `default_discount`,
  `max_discount`,
  `limit_discount`,
  `product_idproduct`
) VALUES
  ('Fruta', 0.02, 0.15, 0.10, 1),
  ('Padaria', 0.03, 0.20, 0.15, 2),
  ('Laticínio', 0.05, 0.25, 0.20, 3),
  ('Valor', 0.04, 0.18, 0.12, 4),
  ('Pasta', 0.03, 0.15, 0.10, 5),
  ('Carne', 0.08, 0.30, 0.25, 6),
  ('Vegetal', 0.02, 0.12, 0.08, 7),
  ('Laticínio', 0.05, 0.25, 0.20, 8),
  ('Café da manhâ', 0.04, 0.20, 0.15, 9),
  ('Peixe', 0.10, 0.35, 0.30, 10);
  
  
INSERT INTO `ForcaVendas`.`store_region` (
`region`, 
`obs`
) VALUES
  ('Norte', 'Observation1'),
  ('Sul', 'Observation2'),
  ('Leste', 'Observation3'),
  ('Oeste', 'Observation4'),
  ('Central', 'Observation5');


INSERT INTO `ForcaVendas`.`adress` (
  `road`,
  `number`,
  `neighborhood`,
  `city`,
  `uf`,
  `type`,
  `store_region_idstore_region`
) VALUES
  ('Rua Principal', '123', 'Centro', 'Cidade1', 'RO', 'Residencial', 1),
  ('Avenida Carvalho', '456', 'Subúrbio', 'Cidade2', 'PR', 'Comercial', 2),
  ('Rua do Bosque', '789', 'Colina', 'Cidade3', 'ES', 'Industrial', 3),
  ('Rua dos Pinheiros', '1011', 'Interior', 'Cidade4', 'MT', 'Residencial', 4),
  ('Avenida Cedro', '1213', 'Beira-Mar', 'Cidade5', 'DF', 'Comercial', 5);
  
  
INSERT INTO `ForcaVendas`.`segments` (
`segment_name`, 
`max_discount`, 
`limit_discount`, 
`default_discount`
) VALUES
  ('Distribuidor', 0, 0, 0.05),
  ('Atacado', 0, 0, 0.08),
  ('Varejo', 0, 0, 0.12);
  
  
INSERT INTO `ForcaVendas`.`stores` (
  `client_legal_name`,
  `client_name`,
  `cnpj`,
  `IE`,
  `type`,
  `client_since`,
  `default_discount`,
  `is_active`,
  `segment_idsegment`,
  `adress_idadress`
) VALUES 
  ('André', 'André LTDA', '12345678901234', 123456, '5','2023-01-01 00:00:00' , 0.05, 1, 1, 1),
  ('Ana', 'Ana LTDA', '23456789012345', 654321, '2', '2023-02-01 00:00:00', 0.08, 1, 2, 2),
  ('Maria', 'Maria LTDA', '34567890123456', 987654, '2', '2023-03-01 00:00:00', 0.06, 1, 3, 3),
  ('Leonardo', 'Leonardo LTDA', '45678901234567', 321654, '1', '2023-04-01 00:00:00', 0.10, 1, 3, 4),
  ('Carlos', 'Carlos LTDA', '56789012345678', 159753, '3', '2023-05-01 00:00:00', 0.07, 1, 1, 5);
  
  
INSERT INTO `ForcaVendas`.`salesman` (
  `store_idstore`,
  `order_idorder`,
  `name`,
  `type`,
  `active`,
  `email`
) VALUES
  (1, 1, 'Vendedor1', 1, 1, 'vendedor1@email.com'),
  (2, 2, 'Vendedor2', 2, 1, 'vendedor2@email.com'),
  (3, 3, 'Vendedor3', 1, 1, 'vendedor1@email.com'),
  (4, 4, 'Vendedor4', 2, 1, 'vendedor2@email.com'),
  (5, 5, 'Vendedor5', 2, 1, 'vendedor2@email.com');

  
INSERT INTO `ForcaVendas`.`orders` (
`dta_emission`
) VALUES
  ('2023-01-10 08:30:00'),
  ('2023-02-15 10:45:00'),
  ('2023-03-20 12:15:00'),
  ('2023-04-25 14:30:00'),
  ('2023-05-30 16:45:00');
  

INSERT INTO `ForcaVendas`.`order_itens` (
`order_idorder`, 
`product_idproduct`, 
`qty`
) VALUES
  (1, 1, 3),
  (2, 2, 2),
  (3, 3, 1),
  (4, 4, 4),
  (5, 5, 2);
  
  
INSERT INTO `ForcaVendas`.`invoice` (
`type`, 
`date`, 
`number`, 
`cfop`, 
`operation`, 
`status`, 
`order_idorder`
) VALUES
  (1, '2023-06-15 10:00:00', 1001, 5401, 'Venda', 1, 1),
  (2, '2023-06-16 11:30:00', 1002, 5402, 'Venda', 1, 2),
  (1, '2023-06-17 12:45:00', 1003, 5403, 'Venda', 1, 3),
  (2, '2023-06-18 14:15:00', 1004, 5404, 'Venda', 1, 4),
  (1, '2023-06-19 15:30:00', 1005, 5405, 'Venda', 1, 5);
#============================================================================================================================================

SELECT 
    *
FROM
    stores;
#--------------------------------------------------
SELECT 
    *
FROM
    order_itens;
#--------------------------------------------------
SELECT 
    *
FROM
    adress;
#--------------------------------------------------
SELECT 
    *
FROM
    categories;
#--------------------------------------------------
SELECT 
    *
FROM
    invoice;
#--------------------------------------------------
SELECT 
    *
FROM
    orders;
#--------------------------------------------------
SELECT 
    *
FROM
    products;
#--------------------------------------------------
SELECT 
    *
FROM
    salesman;
#--------------------------------------------------
SELECT 
    *
FROM
    segments;
#--------------------------------------------------
SELECT 
    *
FROM
    store_region;
#--------------------------------------------------
SELECT 
    *
FROM
    products
WHERE
    name_product LIKE '%ei%';
SELECT 
    *
FROM
    stores
WHERE
    client_since BETWEEN '2023-02-01' AND '2023-04-01';
SELECT 
    *
FROM
    stores
        INNER JOIN
    store_region,
    segments,
    salesman
WHERE
    is_active = 1;
#--------------------------------------------------
SELECT 
    *
FROM
    orders
        INNER JOIN
    order_itens,
    products,
    stores
WHERE
    dta_emission < '2023-03-20';
#--------------------------------------------------
SELECT 
    stores.client_legal_name,
    stores.cnpj,
    stores.ie,
    segments.segment_name,
    adress.road,
    adress.number,
    adress.neighborhood,
    adress.city,
    adress.uf,
    adress.type
FROM
    stores
        INNER JOIN
    segments ON stores.segment_idsegment = segments.idsegment
        INNER JOIN
    adress ON stores.adress_idadress = adress.idadress;

#--------------------------------------------------


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
